name: windows_usb_printer
description: Windows ffi usb handling
version: 0.0.2+4
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/windows_usb_printer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  win32: ^4.1.1
  ffi: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true



